FROM registry.access.redhat.com/ubi8/python-38

WORKDIR /opt/app-root/src

RUN python -m pip install --upgrade pip

RUN git clone https://github.com/sa-mw-dach/dev_demos.git
RUN pip install -r dev_demos/external/licence-plate-workshop/requirements.txt
RUN pip install requests

ENTRYPOINT ["tail", "-f", "/dev/null"]
