FROM docker.io/nvidia/cuda:11.6.2-cudnn8-devel-ubi8

RUN dnf -y install python38 python38-pip
RUN dnf -y install python38-devel
RUN dnf -y install git

RUN mkdir -p /opt/app-root/src 
WORKDIR /opt/app-root/src

RUN python3 -m venv /tmp/.venv
RUN . /tmp/.venv/bin/activate && python -m pip install --upgrade pip

RUN git clone https://github.com/sa-mw-dach/dev_demos.git
RUN . /tmp/.venv/bin/activate && pip install -r dev_demos/external/licence-plate-workshop/requirements.txt
RUN . /tmp/.venv/bin/activate && pip install requests

RUN ln -s /usr/local/cuda/lib64/libcusolver.so.11 /usr/local/cuda/lib64/libcusolver.so.10

ENTRYPOINT ["tail", "-f", "/dev/null"]
