FROM registry.access.redhat.com/ubi8/python-38

WORKDIR /opt/app-root/src

RUN python -m pip install --upgrade pip

RUN pip install -r https://raw.githubusercontent.com/sa-mw-dach/dev_demos/main/external/licence-plate-workshop/requirements.txt
RUN pip install requests

ENTRYPOINT ["tail", "-f", "/dev/null"]
