FROM docker.io/nvidia/cuda:11.6.2-cudnn8-devel-ubi8

RUN dnf -y install python38 python38-pip
RUN dnf -y install python38-devel
RUN dnf -y install git

RUN mkdir -p /opt/app-root/src 
WORKDIR /opt/app-root/src

RUN python -m pip install --upgrade pip

RUN pip install -r https://raw.githubusercontent.com/sa-mw-dach/dev_demos/main/external/licence-plate-workshop/requirements.txt
RUN pip install requests

ENTRYPOINT ["tail", "-f", "/dev/null"]
