FROM registry.access.redhat.com/ubi8/python-38

WORKDIR /opt/app-root/src

RUN python3 -m venv /tmp/.venv
RUN . /tmp/.venv/bin/activate && python -m pip install --upgrade pip

RUN . /tmp/.venv/bin/activate && pip install -r https://raw.githubusercontent.com/sa-mw-dach/dev_demos/main/external/licence-plate-workshop/requirements.txt
RUN . /tmp/.venv/bin/activate && pip install requests

ENTRYPOINT ["tail", "-f", "/dev/null"]
