apiVersion: 1.0.0
metadata:
  generateName: crw_ai_gpu_ag_
components:
  - type: cheEditor
    alias: theia-editor
    id: eclipse/che-theia/latest
    memoryLimit: 1Gi
  - type: chePlugin
    id: ms-python/python/latest
    preferences:
      python.globalModuleInstallation: true
  - mountSources: true
    referenceContent: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: python
      spec:
        containers:
          - name: python
            image: quay.io/manhah/license_plate_demo_gpu_air-gapped:latest
            resources:
              limits:
                memory: 4Gi
                nvidia.com/gpu: 1 # limiting to 1 GPU
              requests:
                nvidia.com/gpu: 1 # requesting 1 GPU
        nodeSelector:
          nvidia.com/gpu.present: true
    type: kubernetes
    alias: python/python
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: redhat/vscode-xml/latest
    type: chePlugin
commands:
  - name: 01_license_plate__1 Run server
    actions:
      - type: exec
        component: python/python
        command: 'cd dev_demos && /bin/bash demos/01_license_plate/run_server.sh'
  - name: 01_license_plate__2 Test AI model
    actions:
      - type: exec
        component: python/python
        command: 'python dev_demos/demos/01_license_plate/test_ai_model.py'
  - name: 01_license_plate__3 Test GPU computation
    actions:
      - type: exec
        component: python/python
        command: 'python dev_demos/demos/01_license_plate/test_gpu.py'
